// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clsxvxnqydegdacrhhbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsc3h2eG5xeWRlZ2RhY3JoaGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNDI0NjIsImV4cCI6MjA4NzkxODQ2Mn0.F5FkE21TnO2aNapOpE0KDVyrv0-zcMcnEzg7z7SuNxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});